USE NacoTikiDB
GO

ALTER DATABASE NacoTikiDB
ADD FILEGROUP Year2016
GO

ALTER DATABASE NacoTikiDB
ADD FILEGROUP Year2017
GO

ALTER DATABASE NacoTikiDB
ADD FILEGROUP Year2018
GO

ALTER DATABASE NacoTikiDB
ADD FILEGROUP Year2019
GO

ALTER DATABASE NacoTikiDB
ADD FILEGROUP Year2020
GO

ALTER DATABASE NacoTikiDB
ADD FILEGROUP Year2021
GO

SELECT name AS AvailableFileGroups
FROM sys.filegroups
WHERE type = 'FG'

ALTER DATABASE NacoTikiDB
ADD FILE
(
	NAME = [Y2016],
	FILENAME = 'D:\NacoTiki_OrderY2016.ndf',
	SIZE = 3072KB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024KB
) TO FILEGROUP [Year2016]
GO

ALTER DATABASE NacoTikiDB
ADD FILE
(
	NAME = [Y2017],
	FILENAME = 'D:\NacoTiki_OrderY2017.ndf',
	SIZE = 3072KB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024KB
) TO FILEGROUP [Year2017]
GO

ALTER DATABASE NacoTikiDB
ADD FILE
(
	NAME = [Y2018],
	FILENAME = 'D:\NacoTiki_OrderY2018.ndf',
	SIZE = 3072KB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024KB
) TO FILEGROUP [Year2018]
GO

ALTER DATABASE NacoTikiDB
ADD FILE
(
	NAME = [Y2019],
	FILENAME = 'D:\NacoTiki_OrderY2019.ndf',
	SIZE = 3072KB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024KB
) TO FILEGROUP [Year2019]
GO

ALTER DATABASE NacoTikiDB
ADD FILE
(
	NAME = [Y2020],
	FILENAME = 'D:\NacoTiki_OrderY2020.ndf',
	SIZE = 3072KB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024KB
) TO FILEGROUP [Year2020]
GO

ALTER DATABASE NacoTikiDB
ADD FILE
(
	NAME = [Y2021],
	FILENAME = 'D:\NacoTiki_OrderY2021.ndf',
	SIZE = 3072KB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1024KB
) TO FILEGROUP [Year2021]
GO

SELECT name as [FileName],
physical_name as [FilePath] 
FROM sys.database_files
where type_desc = 'ROWS'
GO

CREATE PARTITION FUNCTION [Partition_By_Year](DATETIME) 
AS RANGE RIGHT FOR VALUES ('1/1/2017', '1/1/2018', '1/1/2019', '1/1/2020', '1/1/2021')

CREATE PARTITION SCHEME PartitionByYear 
	AS PARTITION [Partition_By_Year]
	TO (Year2016, Year2017, Year2018, Year2019, Year2020, Year2021)
GO

CREATE TABLE DonHangTheoThang
(
	MaDonHang BIGINT,
	TrangThaiThanhToan BIT,
	NgayDat DATETIME,
	ThanhTien BIGINT,
	HinhThucVanChuyen BIGINT,
	PhiVanChuyen BIGINT,
	PRIMARY KEY (MaDonHang, NgayDat)
)
ON PartitionByYear (NgayDat)
GO

INSERT INTO DonHangTheoThang
SELECT MaDonHang, TrangThaiThanhToan, NgayDat, ThanhTien, HinhThucVanChuyen, PhiVanChuyen FROM DonHang


SELECT *
FROM DonHangTheoThang WHERE $PARTITION.Partition_By_Year(NgayDat) = 2
